[project]
name = "jax_guide"
version = "0.1.0"
description = "Add a short description here"
authors = ["Kaze Wong <kazewong.physics@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.6,<3.13"
matplotlib = ">=3.9.2,<3.10"
jaxtyping = ">=0.2.34,<0.3"

[pypi-dependencies]
equinox = ">=0.11.7, <0.12"
diffrax = ">=0.6.0, <0.7"
ipython = ">=8.27.0, <8.28"
jax = {version = ">=0.4.33, <0.5", extras = ["cuda"]}
optax = ">=0.2.3, <0.3"
